import 'package:flutter/material.dart';
import 'package:flutter_paginatrix/flutter_paginatrix.dart';
import 'package:flutter_paginatrix/src/core/constants/paginatrix_skeleton_constants.dart';
import 'package:flutter_paginatrix/src/core/mixins/paginatrix_state_builder_mixin.dart';

/// GridView adapter for Paginatrix using BlocBuilder
///
/// This widget uses [PaginatrixCubit] with [BlocBuilder] for reactive UI updates.
///
/// ## Scroll Direction & Reverse
///
/// When using [reverse] with [scrollDirection]:
/// - **Vertical + reverse**: Grid scrolls from bottom to top
/// - **Horizontal + reverse**: Grid scrolls from right to left
/// - Both combinations are valid but have different UX implications
///
/// ## Example
///
/// ```dart
/// final pagination = PaginatrixController<Pokemon>(
///   loader: repository.loadPokemon,
///   itemDecoder: Pokemon.fromJson,
///   metaParser: ConfigMetaParser(MetaConfig.nestedMeta),
/// );
///
/// PaginatrixGridView<Pokemon>(
///   controller: pagination,
///   gridDelegate: const SliverGridDelegateWithFixedCrossAxisCount(
///     crossAxisCount: 2,
///     crossAxisSpacing: 8,
///     mainAxisSpacing: 8,
///   ),
///   itemBuilder: (context, pokemon, index) {
///     return PokemonCard(pokemon: pokemon);
///   },
/// )
/// ```
///
/// **Note:** You can use either `controller` or `cubit` parameter.
/// `PaginatrixController` is the recommended public API and doesn't
/// require importing `flutter_bloc` directly.
///
/// ## Parameters
///
/// - [controller] or [cubit] - The pagination controller (required, one of them)
/// - [itemBuilder] - Function to build each item widget (required)
/// - [gridDelegate] - Grid layout configuration (required)
/// - [keyBuilder] - Optional function to generate keys for items
/// - [prefetchThreshold] - Number of items from end to trigger next page load
/// - [padding] - Padding around the grid
/// - [physics] - Scroll physics behavior
/// - [shrinkWrap] - Whether the grid should shrink-wrap its contents
/// - [scrollDirection] - Scroll direction (vertical or horizontal)
/// - [reverse] - Whether to reverse the scroll direction
/// - [skeletonizerBuilder] - Custom skeleton loader for initial state
/// - [emptyBuilder] - Custom widget for empty state
/// - [errorBuilder] - Custom widget for error state
/// - [appendErrorBuilder] - Custom widget for append error state
/// - [appendLoaderBuilder] - Custom widget for loading more indicator
/// - [onPullToRefresh] - Callback when user pulls to refresh
/// - [onRetryInitial] - Callback for retrying initial load
/// - [onRetryAppend] - Callback for retrying append operation
/// - [addAutomaticKeepAlives] - Whether to add automatic keep-alives
/// - [addRepaintBoundaries] - Whether to add repaint boundaries
/// - [addSemanticIndexes] - Whether to add semantic indexes
/// - [cacheExtent] - Cache extent for the scroll view
class PaginatrixGridView<T> extends StatelessWidget
    with PaginatrixStateBuilderMixin<T> {
  /// Creates a [PaginatrixGridView] widget.
  ///
  /// The [controller] or [cubit] parameter is required to provide pagination state.
  /// The [itemBuilder] and [gridDelegate] are required to build the grid.
  PaginatrixGridView({
    super.key,
    PaginatrixCubit<T>? cubit,
    PaginatrixController<T>? controller,
    required this.itemBuilder,
    required this.gridDelegate,
    this.keyBuilder,
    this.prefetchThreshold,
    this.padding,
    this.physics,
    this.shrinkWrap = false,
    this.scrollDirection = Axis.vertical,
    this.reverse = false,
    this.skeletonizerBuilder,
    this.emptyBuilder,
    this.errorBuilder,
    this.appendErrorBuilder,
    this.appendLoaderBuilder,
    this.onPullToRefresh,
    this.onRetryInitial,
    this.onRetryAppend,
    this.addAutomaticKeepAlives = true,
    this.addRepaintBoundaries = true,
    this.addSemanticIndexes = true,
    this.cacheExtent,
  }) : cubit = validateAndInitializeCubit<T>(
          cubit: cubit,
          controller: controller,
          scrollDirection: scrollDirection,
        );

  // Required by mixin
  @override
  final PaginatrixCubit<T> cubit;

  /// Function to build each item in the grid.
  ///
  /// Called for each item with the item data, context, and index.
  final Widget Function(BuildContext context, T item, int index) itemBuilder;

  /// Optional function to generate unique keys for items.
  ///
  /// If provided, each item will have a key generated by this function.
  final String Function(T item, int index)? keyBuilder;

  /// Grid layout configuration.
  ///
  /// Defines how items are arranged in the grid (e.g., crossAxisCount, spacing).
  final SliverGridDelegate gridDelegate;

  /// Number of items from the end to trigger loading the next page.
  ///
  /// Defaults to the value from [PaginationOptions.defaultPrefetchThreshold].
  final int? prefetchThreshold;

  /// Padding around the grid.
  @override
  final EdgeInsetsGeometry? padding;

  /// Scroll physics behavior.
  @override
  final ScrollPhysics? physics;

  /// Whether the grid should shrink-wrap its contents.
  ///
  /// Defaults to false.
  @override
  final bool shrinkWrap;

  /// Scroll direction (vertical or horizontal).
  ///
  /// Defaults to [Axis.vertical].
  @override
  final Axis scrollDirection;

  /// Whether to reverse the scroll direction.
  ///
  /// Defaults to false.
  @override
  final bool reverse;

  /// Custom skeleton loader builder for initial loading state.
  ///
  /// If provided, this will be used instead of the default skeletonizer.
  final Widget Function(BuildContext context, int index)? skeletonizerBuilder;

  // Mixin-required callbacks
  /// Custom widget builder for empty state.
  ///
  /// If provided, this will be used instead of the default empty view.
  @override
  final Widget Function(BuildContext context)? emptyBuilder;

  /// Custom widget builder for error state.
  ///
  /// If provided, this will be used instead of the default error view.
  @override
  final Widget Function(BuildContext context, PaginationError error)?
      errorBuilder;

  /// Custom widget builder for append error state.
  ///
  /// If provided, this will be used instead of the default append error view.
  @override
  final Widget Function(BuildContext context, PaginationError error)?
      appendErrorBuilder;

  /// Custom widget builder for loading more indicator.
  ///
  /// If provided, this will be used instead of the default append loader.
  @override
  final Widget Function(BuildContext context)? appendLoaderBuilder;

  /// Callback when user pulls to refresh.
  ///
  /// If provided, this will be called in addition to the default refresh behavior.
  @override
  final VoidCallback? onPullToRefresh;

  /// Callback for retrying initial load.
  ///
  /// If provided, this will be used instead of the default retry behavior.
  @override
  final VoidCallback? onRetryInitial;

  /// Callback for retrying append operation.
  ///
  /// If provided, this will be used instead of the default retry behavior.
  @override
  final VoidCallback? onRetryAppend;

  // GridView performance options
  /// Whether to add automatic keep-alives to grid items.
  ///
  /// Defaults to true.
  @override
  final bool addAutomaticKeepAlives;

  /// Whether to add repaint boundaries to grid items.
  ///
  /// Defaults to true.
  @override
  final bool addRepaintBoundaries;

  /// Whether to add semantic indexes to grid items.
  ///
  /// Defaults to true.
  @override
  final bool addSemanticIndexes;

  /// Cache extent for the scroll view.
  ///
  /// Controls how much content is kept in memory off-screen.
  @override
  final double? cacheExtent;

  // build() method is now in the mixin

  @override
  Widget buildLoadingState(BuildContext context) {
    if (skeletonizerBuilder != null) {
      return createCustomScrollView(
        slivers: [
          SliverGrid(
            delegate: createSliverDelegate(
              builder: skeletonizerBuilder!,
              childCount: PaginatrixSkeletonConstants.defaultItemCount,
            ),
            gridDelegate: gridDelegate,
          ),
        ],
      );
    }

    return PaginatrixGridSkeletonizer(
      padding: padding,
      physics: physics,
      shrinkWrap: shrinkWrap,
      scrollDirection: scrollDirection,
      reverse: reverse,
      gridDelegate: gridDelegate,
    );
  }

  @override
  Widget buildScrollableContent(
      BuildContext context, PaginationState<T> state) {
    final items = state.items;
    final itemCount = items.length;
    final hasMore = state.canLoadMore;
    final isAppending = state.status.maybeWhen(
      appending: () => true,
      orElse: () => false,
    );
    final hasAppendError = state.hasAppendError;

    return createScrollListener(
      prefetchThreshold: prefetchThreshold,
      reverse: reverse,
      child: createCustomScrollView(
        slivers: [
          SliverGrid(
            delegate: createSliverDelegate(
              builder: (context, index) {
                if (index < itemCount) {
                  return buildItem(
                      context, items[index], index, itemBuilder, keyBuilder);
                }
                return const SizedBox.shrink();
              },
              childCount: itemCount,
            ),
            gridDelegate: gridDelegate,
          ),
          // Always show footer when appending or has error, even if no more items
          if (isAppending || hasAppendError)
            SliverToBoxAdapter(
              child: buildFooterItem(
                context,
                hasMore: hasMore,
                isAppending: isAppending,
                hasAppendError: hasAppendError,
                state: state,
              ),
            ),
        ],
      ),
    );
  }
}
