import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:flutter_paginatrix/src/core/extensions/pagination_state_extension.dart';
import 'package:flutter_paginatrix/src/core/entities/pagination_error.dart';
import 'package:flutter_paginatrix/src/core/entities/pagination_state.dart';
import 'package:flutter_paginatrix/src/presentation/controllers/paginated_cubit.dart';
import 'package:flutter_paginatrix/src/presentation/widgets/pagination_skeletonizer.dart';
import 'package:flutter_paginatrix/src/presentation/widgets/paginatrix_state_builder_mixin.dart';

/// ListView adapter for Paginatrix using BlocBuilder
///
/// This widget uses [PaginatrixCubit] with [BlocBuilder] for reactive UI updates.
///
/// ## Scroll Direction & Reverse
///
/// When using [reverse] with [scrollDirection]:
/// - **Vertical + reverse**: List scrolls from bottom to top (chat-like)
/// - **Horizontal + reverse**: List scrolls from right to left (RTL-like)
/// - Both combinations are valid but have different UX implications
///
/// ## Example
///
/// ```dart
/// final pagination = PaginatrixController<Pokemon>(
///   loader: repository.loadPokemon,
///   itemDecoder: Pokemon.fromJson,
///   metaParser: ConfigMetaParser(MetaConfig.nestedMeta),
/// );
///
/// PaginatrixListView<Pokemon>(
///   controller: pagination,
///   itemBuilder: (context, pokemon, index) {
///     return PokemonCard(pokemon: pokemon);
///   },
/// )
/// ```
///
/// **Note:** You can use either `controller` or `cubit` parameter.
/// `PaginatrixController` is the recommended public API and doesn't
/// require importing `flutter_bloc` directly.
///
/// ## Parameters
///
/// - [controller] or [cubit] - The pagination controller (required, one of them)
/// - [itemBuilder] - Function to build each item widget (required)
/// - [keyBuilder] - Optional function to generate keys for items
/// - [prefetchThreshold] - Number of items from end to trigger next page load
/// - [padding] - Padding around the list
/// - [physics] - Scroll physics behavior
/// - [shrinkWrap] - Whether the list should shrink-wrap its contents
/// - [scrollDirection] - Scroll direction (vertical or horizontal)
/// - [reverse] - Whether to reverse the scroll direction
/// - [separatorBuilder] - Optional builder for separators between items
/// - [skeletonizerBuilder] - Custom skeleton loader for initial state
/// - [emptyBuilder] - Custom widget for empty state
/// - [errorBuilder] - Custom widget for error state
/// - [appendErrorBuilder] - Custom widget for append error state
/// - [appendLoaderBuilder] - Custom widget for loading more indicator
/// - [onPullToRefresh] - Callback when user pulls to refresh
/// - [onRetryInitial] - Callback for retrying initial load
/// - [onRetryAppend] - Callback for retrying append operation
/// - [addAutomaticKeepAlives] - Whether to add automatic keep-alives
/// - [addRepaintBoundaries] - Whether to add repaint boundaries
/// - [addSemanticIndexes] - Whether to add semantic indexes
/// - [cacheExtent] - Cache extent for the scroll view
class PaginatrixListView<T> extends StatelessWidget
    with PaginatrixStateBuilderMixin<T> {
  /// Creates a [PaginatrixListView] widget.
  ///
  /// The [controller] or [cubit] parameter is required to provide pagination state.
  /// The [itemBuilder] is required to build each item in the list.
  PaginatrixListView({
    super.key,
    PaginatrixCubit<T>? cubit,
    PaginatrixController<T>? controller,
    required this.itemBuilder,
    this.keyBuilder,
    this.prefetchThreshold,
    this.padding,
    this.physics,
    this.shrinkWrap = false,
    this.scrollDirection = Axis.vertical,
    this.reverse = false,
    this.separatorBuilder,
    this.skeletonizerBuilder,
    this.emptyBuilder,
    this.errorBuilder,
    this.appendErrorBuilder,
    this.appendLoaderBuilder,
    this.onPullToRefresh,
    this.onRetryInitial,
    this.onRetryAppend,
    this.addAutomaticKeepAlives = true,
    this.addRepaintBoundaries = true,
    this.addSemanticIndexes = true,
    this.cacheExtent,
  })  : assert(
          cubit != null || controller != null,
          'Either cubit or controller must be provided',
        ),
        assert(
          scrollDirection == Axis.vertical ||
              scrollDirection == Axis.horizontal,
          'scrollDirection must be either Axis.vertical or Axis.horizontal',
        ),
        cubit = cubit ?? controller!;

  // Required by mixin
  @override
  final PaginatrixCubit<T> cubit;

  /// Function to build each item in the list.
  ///
  /// Called for each item with the item data, context, and index.
  final Widget Function(BuildContext context, T item, int index) itemBuilder;

  /// Optional function to generate unique keys for items.
  ///
  /// If provided, each item will have a key generated by this function.
  final String Function(T item, int index)? keyBuilder;

  /// Number of items from the end to trigger loading the next page.
  ///
  /// Defaults to the value from [PaginationOptions.defaultPrefetchThreshold].
  final int? prefetchThreshold;

  /// Padding around the list.
  final EdgeInsetsGeometry? padding;

  /// Scroll physics behavior.
  final ScrollPhysics? physics;

  /// Whether the list should shrink-wrap its contents.
  ///
  /// Defaults to false.
  final bool shrinkWrap;

  /// Scroll direction (vertical or horizontal).
  ///
  /// Defaults to [Axis.vertical].
  final Axis scrollDirection;

  /// Whether to reverse the scroll direction.
  ///
  /// Defaults to false.
  final bool reverse;

  /// Optional builder for separators between items.
  ///
  /// If provided, separators will be inserted between items.
  final Widget Function(BuildContext context, int index)? separatorBuilder;

  /// Custom skeleton loader builder for initial loading state.
  ///
  /// If provided, this will be used instead of the default skeletonizer.
  final Widget Function(BuildContext context, int index)? skeletonizerBuilder;

  // Mixin-required callbacks
  /// Custom widget builder for empty state.
  ///
  /// If provided, this will be used instead of the default empty view.
  @override
  final Widget Function(BuildContext context)? emptyBuilder;

  /// Custom widget builder for error state.
  ///
  /// If provided, this will be used instead of the default error view.
  @override
  final Widget Function(BuildContext context, PaginationError error)?
      errorBuilder;

  /// Custom widget builder for append error state.
  ///
  /// If provided, this will be used instead of the default append error view.
  @override
  final Widget Function(BuildContext context, PaginationError error)?
      appendErrorBuilder;

  /// Custom widget builder for loading more indicator.
  ///
  /// If provided, this will be used instead of the default append loader.
  @override
  final Widget Function(BuildContext context)? appendLoaderBuilder;

  /// Callback when user pulls to refresh.
  ///
  /// If provided, this will be called in addition to the default refresh behavior.
  @override
  final VoidCallback? onPullToRefresh;

  /// Callback for retrying initial load.
  ///
  /// If provided, this will be used instead of the default retry behavior.
  @override
  final VoidCallback? onRetryInitial;

  /// Callback for retrying append operation.
  ///
  /// If provided, this will be used instead of the default retry behavior.
  @override
  final VoidCallback? onRetryAppend;

  // ListView performance options
  /// Whether to add automatic keep-alives to list items.
  ///
  /// Defaults to true.
  final bool addAutomaticKeepAlives;

  /// Whether to add repaint boundaries to list items.
  ///
  /// Defaults to true.
  final bool addRepaintBoundaries;

  /// Whether to add semantic indexes to list items.
  ///
  /// Defaults to true.
  final bool addSemanticIndexes;

  /// Cache extent for the scroll view.
  ///
  /// Controls how much content is kept in memory off-screen.
  final double? cacheExtent;

  @override
  Widget build(BuildContext context) {
    return BlocBuilder<PaginatrixCubit<T>, PaginationState<T>>(
      bloc: cubit,
      builder: buildContent,
    );
  }

  @override
  Widget buildLoadingState(BuildContext context) {
    if (skeletonizerBuilder != null) {
      return CustomScrollView(
        physics: physics,
        shrinkWrap: shrinkWrap,
        scrollDirection: scrollDirection,
        reverse: reverse,
        cacheExtent: cacheExtent,
        slivers: [
          if (padding != null) SliverPadding(padding: padding!),
          SliverList(
            delegate: SliverChildBuilderDelegate(
              skeletonizerBuilder!,
              childCount: 10,
              addAutomaticKeepAlives: addAutomaticKeepAlives,
              addRepaintBoundaries: addRepaintBoundaries,
              addSemanticIndexes: addSemanticIndexes,
            ),
          ),
        ],
      );
    }

    // Use PaginationSkeletonizer which handles its own CustomScrollView
    return PaginationSkeletonizer(
      padding: padding,
      physics: physics,
      shrinkWrap: shrinkWrap,
      scrollDirection: scrollDirection,
      reverse: reverse,
    );
  }

  @override
  Widget buildScrollableContent(
      BuildContext context, PaginationState<T> state) {
    final items = state.items;
    final itemCount = items.length;
    final hasMore = state.canLoadMore;
    final isAppending = state.status.maybeWhen(
      appending: () => true,
      orElse: () => false,
    );
    final hasAppendError = state.hasAppendError;
    final hasSeparator = separatorBuilder != null;

    return createScrollListener(
      prefetchThreshold: prefetchThreshold,
      reverse: reverse,
      child: CustomScrollView(
        physics: physics,
        shrinkWrap: shrinkWrap,
        scrollDirection: scrollDirection,
        reverse: reverse,
        cacheExtent: cacheExtent,
        slivers: [
          if (padding != null) SliverPadding(padding: padding!),
          SliverList(
            delegate: SliverChildBuilderDelegate(
              (context, index) {
                if (hasSeparator && index > 0) {
                  // Return separator before item (except first item)
                  return Column(
                    mainAxisSize: MainAxisSize.min,
                    children: [
                      separatorBuilder!(context, index - 1),
                      buildItem(context, items[index], index, itemBuilder,
                          keyBuilder),
                    ],
                  );
                }
                return buildItem(
                    context, items[index], index, itemBuilder, keyBuilder);
              },
              childCount: itemCount,
              addAutomaticKeepAlives: addAutomaticKeepAlives,
              addRepaintBoundaries: addRepaintBoundaries,
              addSemanticIndexes: addSemanticIndexes,
            ),
          ),
          // Always show footer when appending or has error, even if no more items
          if (isAppending || hasAppendError)
            SliverToBoxAdapter(
              child: buildFooterItem(
                context,
                hasMore: hasMore,
                isAppending: isAppending,
                hasAppendError: hasAppendError,
                state: state,
              ),
            ),
        ],
      ),
    );
  }
}
